### ISSUE TITLE
Wildcard perm shoud be optional

### ISSUE THREAD

**Issue by zella** [zella/vertx-file-server#3]
```
java.util.NoSuchElementException: key not found: *
	at scala.collection.immutable.Map$Map2.apply(Map.scala:129)
	at org.zella.permissions.impl.FilePermissionCheckerImpl.isPermitted(FilePermissionCheckerImpl.scala:19)

```

**Comment by zella** [comment]
```
java.util.NoSuchElementException: key not found: superPub
	at scala.collection.immutable.Map$Map3.apply(Map.scala:156)
	at org.zella.server.Server.$anonfun$createRouter$3(Server.scala:63)
	at scala.Option.map(Option.scala:146)
	at org.zella.server.Server.$anonfun$createRouter$1(Server.scala:63)

```
